GET  http://localhost:3000/api/v1/products HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmYxYzdlZDM0OTIzNjQ2NWM4MmJlNDciLCJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwicGFzc3dvcmQiOiIkMmEkMTAkczE2Wk1Pd094aVQxL0xRSi9lSFB2ZUlONnBUZ3BCdUhacDJ4RkZVN1lBTnZPeUhkbEZjQVciLCJjcmVhdGVkQXQiOiIyMDIxLTAxLTAzVDEzOjM0OjM3Ljg4M1oiLCJ1cGRhdGVkQXQiOiIyMDIxLTAxLTAzVDEzOjM0OjM3Ljg4M1oiLCJfX3YiOjAsImlhdCI6MTYwOTY4MDg3N30.ms2k8Eo3o-t3OAMLQOCGMjilt1rDsQ7TCUhlS4IFUDo
content-type: application/json
